export const ms = (isMobile, base, mobile) => isMobile ? { ...base, ...mobile } : base;

export const styles = {
  root: {
    "--dm-bg": "#121214",
    "--dm-surface": "#1c1c1f",
    "--dm-surface-bright": "#26262a",
    "--dm-surface-brighter": "#303035",
    "--dm-text": "#e2e2e6",
    "--dm-text-secondary": "#c2c2c8",
    "--dm-text-muted": "#8a8a92",
    "--dm-primary": "#9fa8da",
    "--dm-primary-light": "#c5cae9",
    "--dm-primary-dim": "#5c6bc0",
    "--dm-primary-container": "#1a237e",
    "--dm-on-primary": "#0d0f2b",
    "--dm-on-primary-container": "#c5cae9",
    "--dm-secondary-container": "#2c2c3a",
    "--dm-on-secondary-container": "#d0d0dc",
    "--dm-outline": "#8a8a92",
    "--dm-outline-variant": "#38383e",
    "--dm-error": "#ffb4ab",
    "--dm-error-container": "#3a1510",
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    background: "var(--dm-bg)",
    color: "var(--dm-text)",
    overflow: "hidden",
  },
  topBar: {
    height: 64,
    minHeight: 64,
    display: "flex",
    alignItems: "center",
    padding: "0 16px",
    gap: 10,
    background: "rgba(28, 28, 31, 0.75)",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
    zIndex: 10,
  },
  backBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  stepBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "0 16px 12px",
    flexWrap: "wrap",
  },
  body: {
    flex: 1,
    display: "flex",
    overflow: "hidden",
    gap: 0,
  },
  main: {
    flex: 1,
    overflow: "auto",
    padding: "24px 40px 60px",
  },
  summary: {
    width: 260,
    minWidth: 260,
    padding: 20,
    marginTop: 12,
    overflowY: "auto",
    background: "rgba(28, 28, 31, 0.85)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    borderRadius: "28px 0 0 0",
  },
  stepTitle: {
    fontSize: 24,
    fontWeight: 600,
    letterSpacing: "-0.02em",
    margin: "0 0 8px",
  },
  stepDesc: {
    fontSize: 14,
    color: "var(--dm-text-secondary)",
    margin: "0 0 24px",
    lineHeight: 1.5,
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: 12,
  },
  card: {
    background: "var(--dm-surface)",
    borderRadius: 16,
    padding: 20,
    display: "flex",
    flexDirection: "column",
    gap: 4,
    transition: "border-color 0.2s, background 0.2s",
  },
  cardIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 16,
    background: "var(--dm-surface-bright)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  cardName: { fontSize: 16, fontWeight: 600 },
  cardMeta: { fontSize: 13, color: "var(--dm-text-secondary)" },
  primaryBtn: {
    padding: "10px 24px",
    borderRadius: 20,
    background: "var(--dm-primary)",
    color: "var(--dm-on-primary)",
    fontWeight: 500,
    fontSize: 14,
    display: "inline-flex",
    alignItems: "center",
  },
  secondaryBtn: {
    padding: "10px 24px",
    borderRadius: 20,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "rgba(28, 28, 31, 0.6)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    color: "var(--dm-primary)",
    fontWeight: 500,
    fontSize: 14,
    display: "inline-flex",
    alignItems: "center",
  },
  statBubble: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 36,
    height: 36,
    borderRadius: 12,
    background: "var(--dm-surface-bright)",
    color: "var(--dm-text)",
    fontWeight: 700,
    fontSize: 15,
  },
  statAssign: {
    padding: "4px 10px",
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    background: "var(--dm-surface-bright)",
    color: "var(--dm-text-secondary)",
  },
  statClear: {
    padding: "4px 10px",
    borderRadius: 8,
    fontSize: 12,
    color: "var(--dm-error)",
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
  },
};
